version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: includes orders ids
            tests : 
            - not_null 

          - name: products_id
            description: includes products ids
            tests:
            - not_null
          - name: qty
            description: includes quantities
            # tests:
            # - not_null
          - name: turnover
            description: calculating the turnover
            tests:
            - not_null
          - name: purchase_cost
            description: calculating the purchase costs
            tests:
            - not_null
          - name: margin
            description: calc. the margin
            # tests:
            # - not_null